version: "3.8"

services:
  simplepythonapp:
    build:
      context: .
    container_name: simplepythonapp
    expose:
      - "5000"  # для внутрішньої мережі
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "443:443"
    depends_on:
      - simplepythonapp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

